language: csharp
solution: WebApiCoreSeed.sln
os: linux
dotnet: "1.0.4"
mono: none
pre-install: 
  - sudo apt-get install unzip
  - wget -P ~/tools/ "https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.2.0.1214/sonar-scanner-msbuild-4.2.0.1214-netcoreapp2.0.zip"
  - unzip ~/tools/sonar-scanner-msbuild-4.2.0.1214-netcoreapp2.0.zip -d ~/tools/sonarscaner

install: dotnet restore
script:
  - dotnet ~/tools/sonarscaner/SonarScanner.MSBuild.dll begin /key:makingsensenetcoreseed /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="05f3cb7e227cb06a2c544264aed57186621df170" /d:sonar.organization=making-sense
  - dotnet build
  - dotnet ~/tools/sonarscaner/ end /d:sonar.login="05f3cb7e227cb06a2c544264aed57186621df170"
  - dotnet test WebApiCoreSeed.UnitTests/WebApiCoreSeed.UnitTests.csproj --configuration release --no-build