language: csharp
solution: WebApiCoreSeed.sln
os: linux
dotnet: "1.1.2"
install: dotnet restore
script:
  - dotnet build
  - dotnet test ~/WebApiCoreSeed.UnitTests/WebApiCoreSeed.UnitTests.csproj --configuration release